app/chat/__init__.py
"""
Code permettant de définir l'accès aux routes concernant les fonctions du chat vidéo du blog.
"""

from flask import Blueprint

chat_bp = Blueprint('chat', __name__)

from app.chat import routes

app/chat/routes.py
"""
Code permettant de gérer les routes concernant le chat vidéo du blog.
"""
import os.path
from datetime import datetime

from app.chat import chat_bp

from flask import render_template, flash, redirect, url_for, abort, request
from flask_login import current_user, login_required

from app import db

from app.forms.chatrequest import ChatRequestForm, UserLink

from app.Models.chat_request import ChatRequest
from app.Models.user import User
from app.Models.admin import Admin

from app.mail.routes import send_mail_validate_request, send_mail_refusal_request, \
    send_confirmation_request_reception, send_request_admin

from app.extensions import create_whereby_meeting_admin


# Route permettant d'afficher la vidéo du chat vidéo.
@chat_bp.route('/video_chat/<int:request_id>')
def video_chat(request_id):
    """
    Route permettant d'ouvrir la page de chat vidéo pour une demande spécifique.

    Cette route affiche la page de chat vidéo uniquement si la demande est validée et que la date/heure du rendez-vous
    est proche de l'heure actuelle. Sinon, elle renvoie une erreur et redirige vers la page d'accueil.

    :param request_id: L'identifiant de la demande de chat vidéo.
    :return: La page HTML contenant l'interface de chat vidéo, si les conditions sont remplies.
    """

    # Récupération de la demande de chat vidéo par son identifiant.
    request = ChatRequest.query.get_or_404(request_id)

    # Vérification de la validation de la demande et si la date/heure du rendez-vous est proche de l'heure actuelle.
    now = datetime.now()
    rdv_datetime = datetime.combine(request.date_rdv, request.heure)

    # Vérification pour autoriser l'accès seulement un jour ou une heure avant le rendez-vous.
    if request.status != 'validée' or rdv_datetime > now:
        flash("Le chat vidéo n'est pas encore disponible ou la demande n'est pas validée.", "error")
        return redirect(url_for('landing_page'))

    return render_template('chat_session_user.html', request=request)


# Route permettant de remplir le formulaire afin de demander un chat vidéo.
@chat_bp.route('/demande-chat-video', methods=['GET', 'POST'])
@login_required
def chat_request():
    """"
    Affiche le formulaire permettant à l'utilisateur de demander un chat vidéo.

    Cette route est accessible uniquement aux utilisateurs connectés. Elle instancie le formulaire de demande de chat
    vidéo et le rend disponible à l'utilisateur pour qu'il puisse le remplir.

    :return: Le formulaire de demande de chat vidéo, affiché via le template 'chat/form_request_chat.html'.
    """

    # Instanciation du formulaire.
    formrequest = ChatRequestForm()

    # Intégration du pseudo de l'utilisateur connecté.
    formrequest.pseudo.data = current_user.pseudo

    if not current_user.is_authenticated:
        flash("Vous devez être connecté pour faire une demande de chat vidéo.", "warning")
        return redirect(url_for('auth.login', next=url_for('chat.chat_request')))

    return render_template('chat/form_request_chat.html', formrequest=formrequest)


# Route permettant d'afficher le formulaire de demande de chat
# vidéo et d'enregistrer les informations dans la base de données.
@chat_bp.route('/envoi-demande-chat/<int:user_id>', methods=['GET', 'POST'])
def send_request(user_id):
    """
    Gère la demande de chat vidéo en affichant le formulaire et en enregistrant
    les informations dans la base de données, avec envoi d'emails à l'utilisateur et à l'administrateur.
    """

    formrequest = ChatRequestForm()

    if formrequest.validate_on_submit():
        # Récupération des données du formulaire.
        pseudo = formrequest.pseudo.data
        request_content = formrequest.request_content.data
        date_rdv = formrequest.date_rdv.data
        heure = formrequest.heure.data
        datetime_rdv = datetime.combine(date_rdv, heure)

        # Vérification de la disponibilité de la plage horaire
        conflicting_request = ChatRequest.query.filter_by(date_rdv=date_rdv, heure=heure).first()

        if conflicting_request:
            flash(f"La plage horaire pour le {date_rdv} à {heure} est déjà réservée. Veuillez choisir une autre plage.",
                  "danger")
            return redirect(request.url)

        # Récupération de l'utilisateur et l'administrateur.
        user = User.query.get(user_id)
        if not user:
            abort(404, description="Utilisateur non trouvé")

        admin = Admin.query.first()
        if not admin:
            flash("Aucun administrateur disponible pour traiter la demande.", "error")
            return redirect(url_for('landing_page'))

        # Création d'une nouvelle demande de chat.
        new_request = ChatRequest(
            pseudo=pseudo,
            request_content=request_content,
            date_rdv=date_rdv,
            heure=heure,
            user_id=user_id,
            admin_id=admin.id
        )

        try:
            db.session.add(new_request)
            db.session.commit()

            # Envoi du mail à l'utilisateur.
            send_confirmation_request_reception(user)

            # Envoi du mail à l'administrateur avec le fichier en pièce jointe (si fichier joint).
            send_request_admin(admin, request_content=request_content)

            flash("Demande effectuée avec succès.", "success")

        except Exception as e:
            db.session.rollback()
            flash(f"Erreur lors de l'enregistrement de la demande: {str(e)}", "danger")

    return redirect(url_for('landing_page'))


# Méthode supprimant la demande de chat vidéo du tableau administrateur.
@chat_bp.route('/suppression-demande-chat/<int:id>', methods=['POST'])
def suppress_request(id):
    """
    Supprime une demande de chat vidéo du tableau des demandes administratives.

    Cette route permet à l'administrateur de supprimer une demande de chat vidéo spécifique en fonction de son ID.
    Après la suppression, un message de confirmation est affiché et l'administrateur est redirigé vers la page du calendrier
    des demandes de chat.

    Args:
        id (int): L'identifiant unique de la demande de chat vidéo à supprimer.

    Returns:
        Response: Redirection vers la page du calendrier d'administration après la suppression de la demande.
    """
    # Récupération de la requête à supprimer.
    request = ChatRequest.query.get(id)

    # Vérification de l'existence de la requête.
    if request:
        # Suppression de la requête.
        db.session.delete(request)
        # Enregistrement au sein de la base de données.
        db.session.commit()
        flash(f"La requête de l'utilisateur : {request.pseudo} a été supprimée.")

    return redirect(url_for('admin.calendar'))


# Méthode traitant la demande en attente et la validant.
@chat_bp.route('/validation-demande-chat/<int:id>', methods=['POST'])
def valide_request(id):
    """
    Valide une demande de chat vidéo spécifique et en informe l'utilisateur par e-mail.

    Cette route permet à un administrateur de valider une demande de chat vidéo en attente, identifiée par son ID.
    Après avoir mis à jour le statut de la demande à "validée", un e-mail de confirmation est envoyé à l'utilisateur
    pour l'informer de la validation et lui fournir le lien de la session de chat.

    Args:
        id (int): L'identifiant unique de la demande de chat vidéo à valider.

    Returns:
        Response: Redirection vers la page du calendrier d'administration après la validation de la demande.
    """
    # Récupération de la requête à valider.
    request = ChatRequest.query.get_or_404(id)

    # Vérification de l'existence de la requête.
    if request:
        try:
            # Récupération de l'utilisateur avec son pseudo.
            user = User.query.filter_by(pseudo=request.pseudo).first()

            # Vérification de l'existence de l'utilisateur.
            if not user:
                flash("Utilisateur non trouvé.", "danger")
                return redirect(url_for("admin.calendar"))

            # Validation de la requête.
            request.waiting_request_validate(new_status='validée')
            # Envoi du mail de validation.
            send_mail_validate_request(user, request)

            flash("La demande de chat vidéo a été traitée et validée.", "success")
        except Exception as e:
            # Gestion erreur si erreur.
            flash(f"Une erreur s'est produite lors de la validation: {str(e)}", "danger")
            return redirect(url_for("admin.calendar"))

    return redirect(url_for("admin.calendar"))


# Méthode traitant la demande en attente et la refusant.
@chat_bp.route('/refus-demande-chat/<int:id>', methods=['POST'])
def refuse_request(id):
    """
    Refuse une demande de chat vidéo spécifique et en informe l'utilisateur par e-mail.

    Cette route permet à un administrateur de refuser une demande de chat vidéo en attente, identifiée par son ID.
    Après avoir mis à jour le statut de la demande à "refusée", un e-mail de notification est envoyé à l'utilisateur
    pour l'informer du refus.

    Args:
        id (int): L'identifiant unique de la demande de chat vidéo à refuser.

    Returns:
        Response: Redirection vers la page du calendrier d'administration après le traitement de la demande.
    """
    # Récupération de la requête à refuser.
    request = ChatRequest.query.get_or_404(id)

    # Vérification de l'existence de la requête.
    if request:
        try:
            # Récupération de l'utilisateur avec son pseudo.
            user = User.query.filter_by(pseudo=request.pseudo).first()

            # Vérification de l'existence de l'utilisateur.
            if not user:
                flash("Utilisateur non trouvé.", "danger")
                return redirect(url_for("admin.calendar"))

            # Refus de la requête.
            request.waiting_request_refusal(new_status='refusée')
            # Envoi du mail de refus.
            send_mail_refusal_request(user)

templates/chat/chat_session_admin.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Whereby Meeting</title>
</head>
<body>
    <h1>Rejoignez la réunion Whereby</h1>
    <!-- Intégrer Whereby via iframe -->
    <iframe src="{{ room_url }}" allow="camera; microphone; fullscreen" style="width: 100%; height: 600px; border: 0;"></iframe>
</body>
</html>

templates/chat/chat_session_user.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Whereby Meeting</title>
</head>
<body>
    <h1>Rejoignez la réunion Whereby</h1>
    <!-- Intégrer Whereby via iframe -->
    <iframe src="{{ room_url }}" allow="camera; microphone; fullscreen" style="width: 100%; height: 600px; border: 0;"></iframe>
</body>
</html>

templates/chat/form_request_chat.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description"
      content="Formulaire permettant de demander un chat vidéo avec l'administrateur du site entreprise SethiarWorks.">
<title>{% block title %}Formulaire de demande de chat avec <b>SethiarWorks</b>>.{% endblock %}</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock %}

{% block body_content %}
<div class="outer-frame">
    <div class="inner-frame">
        <!--Titre premier de la section du chat vidéo.-->
        <h2 class="h2-form">Informations concernant la demande de chat vidéo.</h2>

        <div class="space-form"></div>

        <!-- Salutations -->
        <h3 class="h3-form">Bienvenue</h3>

        <div class="annonce">
            <p>
                Si vous souhaitez vous entretenir avec un membre de l'équipe de l'entreprise SethiarWorks
                directement en chat vidéo, vous pouvez remplir ce formulaire.
                Votre demande sera traitée dans les plus brefs délais,
                et nous ferons tout notre possible pour vous aider.
            </p>
            <p>
                Afin de vous faciliter la démarche, nous vous proposons de faire ainsi :
            </p>
            <ul>
                <li>
                    1 - Vous devez préciser une date (Ex : le 15 février)
                    et l'heure à laquelle vous serez disponible.
                </li>
                <li>
                    2 - Après l'envoi de la demande de chat vidéo, vous recevrez un mail vous avertissant que
                    la demande a bien été effectuée et qu'elle est prise en charge.
                </li>
                <li>
                    3 - Suite aux informations données, un membre de SethiarWorks validera le rendez-vous
                    ou vous proposera de renouveler votre demande s'il ne peut se rendre disponible à l'heure choisie.
                </li>
            </ul>
        </div>

        <form method="POST" action="{{ url_for('chat.send_request', user_id=current_user.id) }}" class="form-base"
              enctype="multipart/form-data">

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='Images/images_accueil/logo.jpg') }}" alt="Logo de SethiarWorks"
                     class="avatar-form">
            </div>

            <!-- Titre du formulaire -->
            <h3 class="h3-form">Demande de chat vidéo</h3>

            <!-- Token CSRF pour la sécurité -->
            {{ formrequest.csrf_token }}

            <!-- Conteneur des champs du formulaire -->
            <div class="form-container">

                <!-- Champ pour le pseudo -->
                <div class="form-group">
                    {{ formrequest.pseudo.label }}
                    {{ formrequest.pseudo(class="form-group", readonly=True) }}
                    {% if formrequest.pseudo.errors %}
                    <ul>
                        {% for error in formrequest.pseudo.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <!-- Champ pour le contenu de requête -->
                <div class="form-group">
                    {{ formrequest.request_content.label }} {{ formrequest.request_content(rows=20, cols=20) }}
                    {% if formrequest.request_content.errors %}
                    <ul>
                        {% for error in formrequest.request_content.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <!-- Champ pour la date de visio -->
                <div class="form-group">
                    {{ formrequest.date_rdv.label }} {{ formrequest.date_rdv() }}
                    {% if formrequest.date_rdv.errors %}
                    <ul>
                        {% for error in formrequest.date_rdv.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <!-- Champ pour la date de visio -->
                <div class="form-group">
                    {{ formrequest.heure.label }}
                    {{ formrequest.heure() }}
                    {% if formrequest.heure.errors %}
                    <ul>
                        {% for error in formrequest.heure.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
            <div class="separation1"></div>
            <div class="container-btn">
                <button type="submit" class="validated-btn" aria-label="Valider la visio">Validation de la demande
                </button>
                <a href="{{ url_for('landing_page') }}" class="cancelled-btn">Annulation de la demande et
                    retour à
                    l'accueil</a>
            </div>
        </form>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        flatpickr("input[type='time']", {
            enableTime: true,
            noCalendar: true,
            dateFormat: "H:i",
            time_24hr: true
        });
    });

</script>

{% endblock %}