app/forms/subject_forum.py
"""
Code fournissant les formulaires concernant les sujets du forum du site de l'entreprise SethiarWorks.
"""
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, HiddenField
from wtforms.validators import DataRequired


# Formulaire permettant la création d'un nouveau sujet sur le forum.
class NewSubjectForumForm(FlaskForm):
    """
    Formulaire pour ajouter un nouveau sujet sur le forum.

    Attributes:
        nom (StringField) : Champ pour le nom du sujet pour le forum.

    Example :
        form = NewSubjectForumForm()
    """
    # Nom du sujet.
    nom = StringField(
        "Sujet",
        validators=[DataRequired()],
        render_kw={'placeholder': "Nouveau sujet"}
    )

    # Action de soumettre le formulaire.
    submit = SubmitField("Ajouter le sujet")
    csrf_token = HiddenField()


# Formulaire permettant de supprimer un sujet du forum.
class SuppressSubject(FlaskForm):
    """
    Formulaire pour supprimer un sujet de la section forum.

    Attributes :
        subject_id (HiddenField) : Champ caché pour l'ID du sujet à supprimer.
        submit (SubmitField): Bouton de soumission du formulaire.
    """
    # Champ caché pour l'id du sujet.
    subject_id = HiddenField(
        'Subject_id',
        validators=[DataRequired()]
    )

    # Action de soumettre le formulaire.
    submit = SubmitField('Supprimer')

    # Token de sécurité.
    csrf_token = HiddenField()

app/frontend/__init__.py
"""
Code permettant de définir l'accès aux routes concernant les fonctions administratives du site.
"""

from flask import Blueprint

frontend_bp = Blueprint('frontend', __name__)

from app.frontend import routes

app/frontend/routes.py
"""
Code permettant de définir les routes concernant les fonctions des utilisateurs du site du frontend.
"""

from flask import render_template, abort


from flask_login import current_user

from app.frontend import frontend_bp

from app.forms.subject_forum import NewSubjectForumForm
from app.Models.subject_forum import SubjectForum
from app.Models.comment_subject import CommentSubject
from app.Models.likes_comment_subject import CommentLikeSubject
from app.Models.reply_subject import ReplySubject


from app.forms.form_comment import CommentSubjectForm, CommentLike, SuppressCommentForm, SuppressReplySubject


# Route permettant d'accéder au forum su site entreprise SethiarWoks.
@frontend_bp.route('acces-forum')
def forum():
    """
    Route permettant d'accéder à la page du forum du site.

    :return: templates HTML 'frontend/forum.html.
    """
    # Instanciation du formulaire.
    formsubjectforum = NewSubjectForumForm()

    # Récupération de tous les sujets de la table de données.
    subjects = SubjectForum.query.all()

    # Passage de la valuer booléenne d'authentification.
    is_authenticated = current_user.is_authenticated

    # Debug : Vérification du type.
    print("Type of is_authenticated : ", type(is_authenticated))

    return render_template('frontend/forum.html', formsubjectforum=formsubjectforum, subjects=subjects,
                           is_authenticated=is_authenticated)


# Route afin de visualiser un sujet du forum particulier.
@frontend_bp.route("/acces-sujet-forum/<int:subject_id>", methods=['GET', 'POST'])
def forum_subject(subject_id):
    """
    Route permettant d'accéder à un sujet spécifique du forum.

    Args:
        subject_id (int) : L'identifiant du sujet à afficher.

    Returns :
        Template HTML 'frontend/subject_forum.html' avec les détails du sujet et ses commentaires associés.

    Raises :
        404 error : Si aucun sujet correspondant à l'ID spécifié n'est trouvé dans la base de données.
    """
    # Création de l'instance des formulaires.
    formcomment = CommentSubjectForm()
    formlikecomment = CommentLike()
    formsuppress = SuppressCommentForm()
    formsuppressreply = SuppressReplySubject()

    # Récupération du sujet spécifié par l'ID depuis la base de données.
    subject = SubjectForum.query.get_or_404(subject_id)

    # Passage de la valeur booléenne d'authentification au template.
    is_authenticated = current_user.is_authenticated

    # Debug : Vérification du type.
    print("Type of is authenticated : ", type(is_authenticated))

    # Vérification de l'existence du sujet.
    if not subject:
        # Si le sujet n'existe pas dans la base de données, erreur 404 renvoyée.
        abort(404)

    # Récupération des commentaires associés à ce sujet.
    comment_subject = CommentSubject.query.filter_by(subject_id=subject_id).all()

    # Préparation des données de likes pour chaque commentaire.
    comment_likes_data = {}
    for comment in comment_subject:
        like_count = CommentLikeSubject.query.filter_by(comment_id=comment.id).count()
        liked_user_ids = [like.user_id for like in CommentLikeSubject.query.filter_by(comment_id=comment.id).all()]
        liked_by_current_user = current_user.is_authenticated and current_user.id in liked_user_ids
        comment_likes_data[comment.id] = {
            "like_count": like_count,
            "liked_user_ids": liked_user_ids,
            "liked_by_current_user": liked_by_current_user
        }
    return render_template("frontend/subject_forum.html", subject=subject, subject_id=subject_id,
                               formsuppress=formsuppress, formsuppressreply=formsuppressreply,
                               comment_subject=comment_subject, formcomment=formcomment,
                               formlikecomment=formlikecomment, comment_likes_data=comment_likes_data,
                               is_authenticated=is_authenticated)

templates/frontend/forum.html
{% extends 'base.html.jinja2' %}

{% block head_content %}
<meta name="description"
      content="Forum du site permettant de discuter, interagir et donner son avis sur le site de l'entreprise SethiarWorks.">
<title>{% block title %}Bienvenue sur le forum du blog{% endblock %}</title>
{% endblock %}

{% block header_content %}
{% endblock %}

{% block main_content %}

<!-- conteneur principal -->
<div class="main-content">

    <!-- cadre extérieur -->
    <div class="outer-frame-politique">

        <!-- cadre intérieur -->
        <div class="inner-frame-politique">
            <!-- division de retour à la page d'accueil -->
            <div class="back-link-forum">
                <a class="btn-primary" href="{{ url_for('landing_page') }}">Retour à la page d'accueil</a>
            </div>
            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='Images/images_accueil/logo.jpg') }}" alt="Logo de SethiarWorks"
                     class="avatar-form">
            </div>

            <!--titre -->
            <h1 class="forum-title">Forum de discussion</h1>

            <!-- division pour image forum -->
            <div class="forum-image-container">

                <!-- image centrale -->
                <div class="image-forum">
                    <img src="{{ url_for('static', filename='Images/images_forum/forum1.png') }}"
                         alt="Image forum">
                </div>
            </div>

            <div class="space-form"></div>

            <!-- conteneur d'ajout de catégories -->
            <div class="form-container">
                <h4 class="section-title">Ajouter un sujet</h4>

                <!-- formulaire d'ajout de sujet -->
                <form id="addSubjectForm" method="POST" action="{{ url_for('user.add_subject_forum') }}">

                    <!-- Token CSRF pour la sécurité -->
                    {{ formsubjectforum.csrf_token }}

                    <!-- Champ pour le nouveau sujet -->
                    <div class="form-group">
                        {{ formsubjectforum.nom.label }}
                        {{ formsubjectforum.nom(size=20) }}
                    </div>

                    <!-- bouton de soumission du formulaire -->
                    <button type="submit" class="btn-primary-forum">
                        {{ formsubjectforum.submit.label }}
                    </button>
                </form>
            </div>
            <div class="space2"></div>

            <!-- Liste des sujets -->
            <div class="subjects-container">
                <h4 class="section-title">Sujets disponibles</h4>

                <!--tableau des sujets -->
                <table class="subjects-table">
                    <thead>
                    <tr>
                        <th>Sujet</th>
                        <th>Auteur</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for subject in subjects %}
                    <tr>
                        <td class="subject-name">{{ subject.nom }}</td>
                        <td class="subject-author">{{ subject.author }}</td>
                        <td><a href="{{ url_for('frontend.forum_subject', subject_id=subject.id) }}"
                               class="btn-secondary-forum">Voir</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block footer_content %}
<script>
document.addEventListener('DOMContentLoaded', function() {
    var form = document.getElementById('addSubjectForm');

    // Variable JavaScript indiquant si l'utilisateur est connecté
    var isAuthenticated = {{ is_authenticated|tojson }};

    form.addEventListener('submit', function(event) {
        if (!isAuthenticated) {
            // Afficher une alerte si l'utilisateur n'est pas connecté
            alert("Vous devez être connecté pour ajouter un sujet.");
            event.preventDefault(); // Empêche la soumission du formulaire
            }
    });
});





</script>
{% endblock %}

templates/frontend/subject_forum.html
{% extends 'base.html.jinja2' %}

{% block head_content %}
<meta name="description"
      content="Forum du site permettant de discuter, interagir et donner son avis sur le site de l'entreprise SethiarWorks.">
<title>{% block title %}Bienvenue sur le forum du blog{% endblock %}</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.34/moment-timezone-with-data.min.js"></script>
{{ moment.include_moment() }}
{% endblock %}

{% block header_content %}
{% endblock %}

{% block main_content %}

<!-- Conteneur principal -->
<div class="main-content">

    <!-- Cadre extérieur -->
    <div class="outer-frame-politique">

        <!-- Cadre intérieur -->
        <div class="inner-frame-politique">

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='Images/images_accueil/logo.jpg') }}" alt="Logo de SethiarWorks"
                     class="avatar-form">
            </div>

            <!--Titre -->
            <h1 class="forum-title">Forum de discussion</h1>

            <!-- Division pour image forum -->
            <div class="forum-image-container">

                <!-- Image centrale -->
                <div class="image-forum">
                    <img src="{{ url_for('static', filename='Images/images_forum/forum1.png') }}"
                         alt="Image forum">
                </div>
            </div>

            <div class="space-form"></div>

            <!-- Séparation -->
            <hr class="politique-divider">

            <!-- Conteneur du sujet -->
            <div class="container-subject-forum">
                <h2 class="forum-subtitle">
                    Discussion sur le sujet : <span class="subject-name">{{ subject.nom }}</span>
                </h2>
            </div>

            <!-- Conteneur principal des commentaires -->
            <div class="container-comment">

                <!-- Conteneur commentaire -->
                <div class="comment-avis">
                    <h3 class="forum-subtitle">Vous pouvez laisser un commentaire :</h3>
                </div>

                <!-- Conteneur formulaire du commentaire -->
                <div class="form-comment">
                    <form id="addCommentSubject" method="POST"
                          action="{{ url_for('user.comment_subject', user_pseudo=current_user.pseudo, subject_id=subject.id) }}">
                        {{ formcomment.csrf_token }}
                        <input type="hidden" name="subject_id" value="{{ subject.id }}">
                        <input type="hidden" name="user_pseudo" value="{{ current_user.pseudo }}">
                        <textarea name="comment_content" placeholder="Votre commentaire" required></textarea>
                        <button class="btn-comment" type="submit">Poster le commentaire</button>
                    </form>
                </div>
            </div>

            {% for comment in comment_subject %}

            <!-- Conteneur pour poster un commentaire -->
            <div class="comment">

                <!-- Conteneur de la photo de l'utilisateur-->
                <div class="comment-header">
                    <img src="{{ url_for('user.profil_photo', user_id=comment.user_id) }}" alt="Photo de profil"
                         class="profile-picture">
                    <div class="comment-user-info">
                        <strong class="user-pseudo">{{ comment.user.pseudo }}</strong>
                        <span class="user-role">{{ comment.user.role }} a commenté :</span>
                        <small class="comment-date">
                            Le {{ moment(comment.comment_date).format('DD-MM-YYYY à HH:mm') }}
                        </small>
                    </div>
                </div>

                <!-- Conteneur du contenu du commentaire -->
                <div class="comment-body">
                    <p class="content-comment">
                        {{ comment.comment_content | replace('\n', '<br>') | safe }}
                    </p>
                </div>

                <!-- Conteneur des modifications au commentaire -->
                {% if comment.user_id == current_user.id %}
                <div class="comment-actions">

                    <!-- Lien vers la modification du commentaire -->
                    <a href="{{ url_for('user.change_comment', id=comment.id) }}" class="change-button">
                        Modifier le commentaire
                    </a>

                    <!-- Formulaire de suppression du commentaire -->
                    <form action="{{ url_for('user.delete_comment', id=comment.id) }}" method="POST"
                          class="delete-comment-form" style="margin-left:10%;display:inline;">
                        <!-- Token CSRF pour la sécurité -->
                        {{ formsuppress.csrf_token }}

                        <!-- Utilisation d'un bouton pour la suppression -->
                        <button type="submit" class="suppress-button"
                                onclick="return confirm('Êtes-vous certain-e de vouloir supprimer votre commentaire ?'); ">
                            Supprimer le commentaire
                        </button>
                    </form>
                </div>
                {% endif %}
            </div>

            <!-- Conteneur de réponse à un commentaire -->
            <div class="reply-button-container">

                <!-- lien permettant de répondre à un commentaire -->
                <a href="{{ url_for('user.reply_form_subject', comment_id=comment.id, user_pseudo=current_user.pseudo) }}"
                   class="reply-button">
                    Répondre
                </a>

                <!-- conteneur permettant de liker un commentaire -->
                <div class="like-section" data-user-id="{{ current_user.pseudo }}">

                    <!-- formulaire permettant de liker un commentaire -->
                    <form id="formlikecomment" method="POST"
                          action="{{ url_for('user.likes_comment_subject') }}" style="display: none;">

                        <!-- Token CSRF pour la sécurité -->
                        {{ formlikecomment.csrf_token }}
                        <input type="hidden" name="comment_id" value="{{ comment.id }}">
                        <input type="hidden" name="user_pseudo" value="{{ current_user.pseudo }}">
                        <button type="submit" class="like-submit"></button>
                    </form>

                    <!-- conteneur de l'icône du like -->
                    <div class="like-icon" data-comment-id="{{ comment.id }}"
                         onclick="toggleLike(this, '{{ comment.id }}', '{{ current_user.pseudo }}')">
                        {% if comment_likes_data[comment.id].liked_by_current_user %}

                        <!-- Icône pour un cœur plein -->
                        &#9829;
                        {% else %}
                        <!-- Icône pour un cœur vide -->
                        &#9825;
                        {% endif %}
                    </div>

                    <!-- conteneur de l'utilisateur qui a liké -->
                    <div class="liked-users">
                        <p id="like-message-{{ comment.id }}">
                            {% set like_data = comment_likes_data[comment.id] %}
                            {% if like_data.like_count == 1 %}
                            1 utilisateur a aimé le commentaire.
                            {% elif like_data.like_count > 1 %}
                            {{ like_data.like_count}} utilisateurs ont aimé le commentaire.
                            {% else %}
                            Personne n'a aimé le commentaire pour le moment.
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>

            <!-- Conteneur principal de réponses au commentaire-->
            <div class="replies-container">
                {% for reply in comment.replies %}

                <!-- Conteneur d'une réponse individuelle -->
                <div class="reply-card">

                    <!-- Conteneur de la photo de l'utilisateur qui a répondu -->
                    <div class="reply-header">
                        <img src="{{ url_for('user.profil_photo', user_id=reply.user_id) }}"
                             alt="Photo de profil" class="reply-profile-picture">

                        <!-- Conteneur du pseudo de l'utilisateur qui a répondu -->
                        <div class="reply-info">
                            <strong class="reply-user-pseudo">{{ reply.user.pseudo }}</strong>
                            <span class="reply-user-role">{{ reply.user.role }} a répondu :</span>
                            <small class="reply-date">
                                Le {{ moment(reply.reply_date).format('DD-MM-YYYY à HH:mm') }}
                            </small>
                        </div>
                    </div>

                    <!-- Contenu de la réponse -->
                    <div class="reply-body">
                        <p class="reply-content">
                            {{ reply.reply_content | replace('\n', '<br>') | safe }}
                        </p>
                    </div>

                    <!-- conteneur permettant de changer le contenu de la réponse -->
                    <div class="reply-actions">
                        {% if reply.user_id == current_user.id %}

                        <!-- lien vers la modification de la réponse -->
                        <a href="{{ url_for('user.change_reply', id=reply.id) }}" class="change-button"
                           style="margin-left:10%;">
                            Modifier la réponse
                        </a>

                        <!-- formulaire de suppression de la réponse -->
                        <form action="{{ url_for('user.delete_reply', id=reply.id) }}" method="POST"
                              class="delete-comment-form" style="margin-left:10%;display:inline;">
                            <!-- Token CSRF pour la sécurité -->
                            {{ formsuppressreply.csrf_token }}

                            <!-- Utilisation d'un bouton pour la suppression -->
                            <button type="submit" class="suppress-button"
                                    onclick="return confirm('Êtes-vous certain-e de vouloir supprimer votre réponse ?');">
                                Supprimer le commentaire
                            </button>
                        </form>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endfor %}
        </div>

        <!-- Séparation -->
        <hr class="politique-divider">

        <!-- division de retour à la page d'accueil -->
        <div class="back-link-forum">
            <a class="btn-primary" href="{{ url_for('frontend.forum') }}">Retour au forum</a>
        </div>
    </div>
</div>


{% endblock %}

{% block footer_content %}

<script src="{{ url_for('static', filename='javascript/like_comment_subject.js') }}"></script>

<script>
document.addEventListener('DOMContentLoaded', function() {
    var form = document.getElementById('addCommentSubject');

    // Variable JavaScript indiquant si l'utilisateur est connecté
    var isAuthenticated = {{ is_authenticated|tojson }};

    form.addEventListener('submit', function(event) {
        if (!isAuthenticated) {
            // Afficher une alerte si l'utilisateur n'est pas connecté
            alert("Vous devez être connecté pour ajouter un commentaire à ce sujet.");
            event.preventDefault(); // Empêche la soumission du formulaire
            }
    });
});
</script>

{% endblock %}