app/forms/user_login.py
"""
Code permettant de se connecter en tant qu'utilisateur.
"""

from flask_wtf import FlaskForm

from wtforms import StringField, SubmitField, PasswordField, HiddenField
from wtforms.validators import DataRequired


class UserConnection(FlaskForm):
    """
    Formulaire de connexion pour les clients de l'entreprise afin de laisser un commentaire
    .

    Attributes :
        pseudo (StringField) : champ pour le pseudo du client utilisateur.
        password (PasswordField) : champ pour le password de l'utilisateur.
        submit (SubmitField) : Bouton de soumission du commentaire.
        csrf_token (HiddenField) : Jeton CSRF pour la sécurité des formulaires.
    """

    # Champ pour le pseudo.
    pseudo = StringField(
        "Pseudo Utilisateur",
        validators=[DataRequired()],
        render_kw={"placeholder": "Votre Pseudo"}
    )

    # Champ pour le password.
    password = PasswordField(
        "Mot de passe utilisateur",
        validators=[DataRequired()],
        render_kw={"placeholder": "Votre mot de passe"}
    )

    # Action de soumettre le formulaire.
    submit = SubmitField("Se connecter")

    # Token de sécurité.
    csrf_token = HiddenField()

app/devis/__init__.py
"""
Code permettant de définir l'accès aux routes concernant les fonctions des devis du site.
"""

from flask import Blueprint

devis_bp = Blueprint('devis', __name__)

from app.devis import routes

app/devis/routes.py
"""
Code permettant de gérer les demandes de devis
"""

from app.devis import devis_bp

from flask import flash, redirect, url_for
from app import db

from app.mail.routes import mail_reply_devis_reject, mail_reply_devis_validate

from app.Models.devis_request import DevisRequest


# Méthode supprimant la demande de chat vidéo du tableau administrateur.
@devis_bp.route('/suppression-demande-devis/<int:id>', methods=['POST'])
def suppress_devis(id):
    """
    Supprime une demande de devis du tableau des demandes administratives.

    Cette route permet à l'administrateur de supprimer une demande de devis spécifique en fonction de son ID.
    Après la suppression, un message de confirmation est affiché et l'administrateur est redirigé vers la
    page de la liste des devis du site.

    Args:
        id (int): L'identifiant unique de la demande de devis à supprimer.

    Returns:
        Response: Redirection vers la page de la liste des devis après la suppression du devis.
    """
    try:
        # Récupération du devis à supprimer.
        devis = DevisRequest.query.get(id)

        # Vérification de l'existence du devis.
        if not devis:
            flash("La demande de devis n'a pas été trouvée.", "danger")
            return redirect(url_for('admin.list_devis'))

        # Suppression du devis.
        db.session.delete(devis)

        # Enregistrement au sein de la base de données.
        db.session.commit()

        # Message de confirmation après la suppression.
        flash(f"La requête de l'utilisateur : {devis.nom} {devis.prenom} a été supprimée.", "success")

    except Exception as e:
        # Gestion des erreurs et annulation des changements si nécessaire.
        db.session.rollback()  # Annulation des modifications en cas d'erreur.
        flash(f"Une erreur s'est produite lors de la suppression : {str(e)}", "danger")

    finally:
        # Fermeture de la session de base de données.
        db.session.close()

    return redirect(url_for('admin.list_devis'))


# Méthode générique pour traiter une demande de devis.
def process_devis(id, action):
    """
    Traite une demande de devis en fonction de l'action spécifiée (valider ou refuser)
    et en informe l'utilisateur par e-mail.

    Args:
        id (int): L'identifiant unique de la demande de devis.
        action (str): L'action à effectuer, soit "valider" ou "refuser".

    Returns:
        Response: Redirection vers la page de la liste des devis après traitement.
    """
    # Récupération de la demande de devis.
    devis = DevisRequest.query.get_or_404(id)

    try:
        # Mise à jour du statut selon l'action.
        if action == "valider":
            devis.waiting_request_validate(new_status="validée")
            mail_reply_devis_validate(devis.email, devis.prenom)
            flash("La demande de devis a été traitée et validée.", "success")
        elif action == "refuser":
            devis.waiting_request_refusal(new_status="refusée")
            mail_reply_devis_reject(devis.email, devis.prenom)
            flash("La demande de devis a été traitée et refusée.", "success")
        else:
            flash("Action inconnue pour traiter la demande.", "danger")
            return redirect(url_for("admin.list_devis"))

        # Sauvegarde des modifications dans la base de données.
        db.session.commit()

    except Exception as e:
        # Gestion des erreurs lors du traitement.
        flash(f"Une erreur s'est produite : {str(e)}", "danger")
        # Annule les changements si une erreur survient.
        db.session.rollback()

    finally:
        # Fermeture de la session de base de données.
        db.session.close()

    return redirect(url_for("admin.list_devis"))


# Route pour valider une demande de devis.
@devis_bp.route('/validation-demande-devis/<int:id>', methods=['POST'])
def valide_devis(id):
    """

    :param id:
    :return:
    """
    return process_devis(id, "valider")


# Route pour refuser une demande de devis.
@devis_bp.route('/refus-demande-devis/<int:id>', methods=['POST'])
def refuse_devis(id):
    """

    :param id:
    :return:
    """
    return process_devis(id, "refuser")

app/user/__init__.py
"""
Code permettant de définir l'accès aux routes concernant les fonctionnalités utilisateur.
"""

from flask import Blueprint

user_bp = Blueprint('user', __name__)

from app.user import routes

app/user/routes.py
"""
Code permettant de définir les routes concernant les fonctions des utilisateurs du blog comme l'enregistrement
et l'accès aux formulaires.
"""
import bcrypt

from PIL import Image
from io import BytesIO
from markupsafe import escape

from datetime import datetime

from app.user import user_bp

from app.Models import db

from flask import render_template, redirect, url_for, request, flash, jsonify
from flask_login import login_required, current_user

from app.forms.user_registration import UserRecording
from app.forms.subject_forum import NewSubjectForumForm
from app.forms.devisrequest import DevisRequestForm
from app.forms.form_comment import ChangeCommentSubjectForm, SuppressCommentForm, \
    ReplySubjectForm, ChangeReplySubject, SuppressReplySubject

from app.Models.user import User
from app.Models.subject_forum import SubjectForum
from app.Models.comment_subject import CommentSubject
from app.Models.likes_comment_subject import CommentLikeSubject
from app.Models.reply_subject import ReplySubject

from app.Models.devis_request import DevisRequest

from app.mail.routes import mail_reply_forum_comment, mail_like_comment_subject, \
    send_mail_validate_demand, send_mail_inform_demand, send_confirmation_email_admin

from app.extensions import allowed_file


# Route permettant l'affichage du formulaire d'inscription utilisateur.
@user_bp.route("/inscription-client-formulaire", methods=['GET', 'POST'])
def user_registration():
    """
    Route permettant d'afficher le formulaire d'inscription de l'utilisateur
    Gère l'enregistrement d'un nouvel utilisateur. Cette fonction traite à la fois les
    requêtes GET et POST. Lors d'une requête GET, elle affiche le formulaire
    d'enregistrement. Lors d'une requête POST, elle traite les données soumises par
    l'utilisateur, valide le formulaire, gère le fichier de photo de profil, redimensionne
    l'image et enregistre les informations de l'utilisateur dans la base de données.

    :return: Redirection vers la page de confirmation de l'email si l'inscription est réussie,
             sinon redirection vers la page d'enregistrement avec un message d'erreur.
    """
    # Instanciation du formulaire.
    form_usersaving = UserRecording()

    # Vérification de la soumission du formulaire.
    if form_usersaving.validate_on_submit():
        # Assainissement des données.
        pseudo = form_usersaving.pseudo.data
        password_hash = form_usersaving.password.data
        email = form_usersaving.email.data
        date_naissance = form_usersaving.date_naissance.data

        salt = bcrypt.gensalt()
        password_hash = bcrypt.hashpw(password_hash.encode('utf-8'), salt)

        # Vérification de la soumission du fichier.
        if 'profil_photo' not in request.files or request.files['profil_photo'].filename == '':
            flash("Aucune photo de profil fournie.", "error")
            return redirect(url_for('user.user_registration'))

        profil_photo = request.files['profil_photo']
        if profil_photo and allowed_file(profil_photo.filename):
            photo_data = profil_photo.read()

            # Redimensionnement de l'image avec Pillow.
            try:
                img = Image.open(BytesIO(photo_data))
                img.thumbnail((75,75))
                img_format = img.format if img.format else 'JPEG'
                output = BytesIO()
                img.save(output, format=img_format)
                photo_data_resized = output.getvalue()
            except Exception as e:
                flash(f"Erreur lors du redimensionnement de l'image : {str(e)}", "error")
                return redirect(url_for("user.user_registration"))

            if len(photo_data_resized) > 5 * 1024 * 1024:  # 5Mo
                flash("Le fichier est trop grand (Maximum 5Mo).", "error")
                return redirect(url_for("user.user_registration"))
            photo_data = profil_photo.read()

        else:
            flash("Type de fichier non autoriosé.", "error")
            return redirect(url_for("user.user_registration"))

        new_user = User(
            pseudo=pseudo,
            password_hash=password_hash,
            salt=salt,
            email=email,
            date_naissance=date_naissance,
            # Stockage des données binaires de l'image.
            profil_photo=photo_data_resized
            )

        try:
            db.session.add(new_user)
            db.session.commit()
            flash('Inscription réussie ! Vous pouvez maintenant vous connecter.')
            send_confirmation_email_admin()
            return redirect(url_for("mail.send_confirmation_email_user", email=email))
        except Exception as e:
            db.session.rollback()
            flash(f"Erreur lors de l'enregistrement de l'utilisateur: {str(e)}", "error")
        finally:
            db.session.close()

    return render_template('user/user_registration.html', form_usersaving=form_usersaving)


# Méthode permettant de visualiser la photo de l'utilisateur.
@user_bp.route("/profil_photo/<int:user_id>")
def profil_photo(user_id):
    """
    Affiche la photo de profil d'un utilisateur.

    :param user_id : L'identifiant de l'utilisateur.

    :return : L'image de la photo de profil en tant que réponse HTTP avec le type MIME approprié.
    """
    user = User.query.get_or_404(user_id)
    if user.profil_photo:
        return user.profil_photo, {'Content-Type': 'image/jpeg'}
    else:
        return "No image found", 404


# Route permettant de remplir un formulaire pour un devis.
@user_bp.route("/formulaire-demande-devis", methods=['GET', 'POST'])
def devis():
    """
    Permet à un utilisateur de remplir un formulaire.

    Returns :
        Formulaire pour renseigner un devis (devis_form.html)
    """
    return render_template("user/devis_form.html")


# Route permettant d'ajouter un sujet au forum une fois connecté.
@user_bp.route("/forum/ajouter-sujet", methods=['POST'])
@login_required
def add_subject_forum():
    """
    Permet à un utilisateur de créer un nouveau sujet pour le forum.

    Returns :
        redirect : Redirige vers la page du forum après avoir ajouté le sujet.
    """

    # Création de l'instance du formulaire.
    formsubjectforum = NewSubjectForumForm()

    # Passage de la valeur booléenne d'authentification au template.
    is_authenticated = current_user.is_authenticated
    author = current_user.pseudo

    # Debug: Vérification du type.
    print("Type of is_authenticated:", type(is_authenticated))

    if request.method == "POST":
        # Saisie du nom du sujet.
        nom_subject_forum = escape(request.form.get("nom"))
        subject_forum = SubjectForum(nom=nom_subject_forum, author=current_user.pseudo)

        # Enregistrement du sujet dans la base de données.
        db.session.add(subject_forum)
        db.session.commit()

    # Récupération de tous les sujets après l'ajout du nouveau sujet.
    subjects = SubjectForum.query.all()

    return render_template("frontend/forum.html", formsubjectforum=formsubjectforum, subjects=subjects,
                           is_authenticated=is_authenticated) + '#sujet'


# Route permettant de commenter un sujet du forum.
@user_bp.route("/forum/commentaires-sujet", methods=['POST'])
@login_required
def comment_subject():
    """
    Permet à un utilisateur connecté de laisser un commentaire sur un sujet du forum.

    Returns :
         redirect : Redirige vers la page du sujet du forum après avoir laissé un commentaire.
    """
    # Passage de la valeur booléenne d'authentification au template.
    is_authenticated = current_user.is_authenticated

    # Debug: Vérification du type.
    print("Type of is_authenticated:", type(is_authenticated))

    # Utilisation de current_user pour obtenir le pseudo et l'ID utilisateur.
    user_pseudo = current_user.pseudo
    user_id = current_user.id

    # Obtention de l'id du sujet du forum à partir de la requête POST.
    subject_id = request.form.get("subject_id")
    comment_content = request.form.get("comment_content")

    # Vérification que le sujet et le contenu du commentaire existent.
    if not subject_id or not comment_content:
        flash("L'identifiant du sujet ou le contenu du commentaire est manquant.", "error")
        return redirect(url_for("frontend.forum"))  # Redirige vers la page du forum ou une page d'erreur appropriée.

    # Création d'un nouvel objet de commentaire avec les données actuelles.
    new_comment = CommentSubject(comment_content=comment_content, user_id=user_id, subject_id=subject_id)

    # Ajouter le nouveau commentaire à la base de données.
    db.session.add(new_comment)
    db.session.commit()

    # Redirection sur la page d'affichage des sujets après ajout du commentaire.
    return redirect(url_for("frontend.forum_subject", subject_id=subject_id, is_authenticated=is_authenticated))


# Route permettant à un utilisateur de modifier son commentaire dans la section forum.
@user_bp.route('/modification-commentaire-utilisateur/<int:id>', methods=['GET', 'POST'])
@login_required
def change_comment(id):
    """
    Permet à un utilisateur de modifier son commentaire.

    Args:
        id (int): L'id du commentaire à modifier.

    Returns:
        redirect: Redirige vers la page du sujet du forum après modification du commentaire.
    """
    comment = CommentSubject.query.filter_by(id=id).first_or_404()

    # Vérification que l'utilisateur actuel est l'auteur du commentaire
    if comment.user_id != current_user.id:
        flash('Vous n\'êtes pas autorisé à modifier ce commentaire.')
        return redirect(url_for('frontend.forum_subject', subject_id=comment.subject_id))

    formchange = ChangeCommentSubjectForm(obj=comment)

    if formchange.validate_on_submit():
        comment.comment_content = formchange.comment_content.data
        db.session.commit()
        flash('Commentaire modifié avec succès.')

templates/user/devis.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
    <meta name="description" content="Devis concernant un produit de l'entreprise SethiarWorks d'Arnaud Lefetey.">
    <title>{% block title %}Demande de devis entreprise SethiarWorks{% endblock %}</title>
{% endblock %}

<div class="container-form">
    <form class="devis">

    </form>
</div>

templates/user/devis_form.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description"
      content="Obtenez rapidement un devis personnalisé pour votre projet avec SethiarWorks, expert en développement et conception numérique.">
<title>{% block title %}Demande de devis entreprise SethiarWorks{% endblock %}</title>
{% endblock %}

{% block body_content %}
<div class="outer-frame">
    <div class="inner-frame">
        <h1 class="h1-devis">Demande de devis</h1>
        <div class="space2"></div>
        <div class="annonce">

            <!-- Titre -->
            <h2 class="h2-devis">
                Bienvenue sur la demande de devis.
            </h2>
            <div class="space2"></div>

            <!-- Présentation -->
            <ul>
                <li><b>Rapidité :</b> Réponse garantie sous une semaine.</li>
                <li><b>Clarté :</b> Décrivez votre projet avec les fonctionnalités attendues.</li>
                <li><b>Transparence :</b> Consultez nos <a href="{{url_for('functional.politique')}}">conditions
                    générales</a>.
                </li>
            </ul>
            <div class="space2"></div>

            <!--Champ de précision -->
            <p>
                Pour tout renseignement supplémentaire, vous pouvez consulter nos
                <b><a href="{{url_for('functional.politique')}}">conditions générales d'utilisation</a></b>
                ou nos <b><a href="{{url_for('functional.mentions')}}">mentions légales</a></b>.
            </p>
        </div>

        <form method="POST" action="{{ url_for('user.user_devis_demand') }}" class="form-base"
              enctype="multipart/form-data">

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='Images/images_accueil/logo.jpg') }}" alt="Logo de SethiarWorks"
                     class="avatar-form">
            </div>

            <!-- Titre du formulaire -->
            <h3 class="h3-form">Demande de devis</h3>

            <!-- Token CSRF pour la sécurité -->
            {{ form_devis.csrf_token }}

            <div class="space-form"></div>

            <!-- Conteneur des champs du formulaire -->
            <div class="form-container">

                <!-- Champ pour le nom et le prénom-->
                <div class="form-group">
                    {{ form_devis.nom.label }} {{ form_devis.nom() }}
                    {% if form_devis.nom.errors %}
                    <ul>
                        {% for error in form_devis.nom.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    {{ form_devis.prenom.label }} {{ form_devis.prenom() }}
                    {% if form_devis.prenom.errors %}
                    <ul>
                        {% for error in form_devis.prenom.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <!-- Champ pour le numéro de téléphone-->
                <div class="form-group">
                    {{ form_devis.telephone.label }} {{ form_devis.telephone() }}
                    {% if form_devis.telephone.errors %}
                    <ul>
                        {% for error in form_devis.telephone.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <!-- Champ pour le mail -->
                <div class="form-group">
                    {{ form_devis.email.label }} {{ form_devis.email() }}
                    {% if form_devis.email.errors %}
                    <ul>
                        {% for error in form_devis.email.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <!-- Champ pour le type de projet -->
                <div class="form-group">
                    {{ form_devis.project_type.label }} {{ form_devis.project_type() }}
                    {% if form_devis.project_type.errors %}
                    <ul>
                        {% for error in form_devis.project_type.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <!-- Conteneur du contenu de la demande de devis -->
                <div class="form-group">
                    {{ form_devis.demand_content.label }}
                    {{ form_devis.demand_content(class="form-control",
                    placeholder="Votre description de votre projet") }}

                    {% if form_devis.demand_content.errors %}
                    <ul>
                        {% for error in form_devis.demand_content.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

            </div>
            <div class="space2"></div>

            <div class="separation1"></div>

            <div class="space2"></div>

            <!-- Conteneur des boutons du formulaire -->
            <div class="container-btn">
                <button type="submit" class="validated-btn" aria-label="Valider la demande de devis">Validation de la
                    demande de devis
                </button>
                <a href="{{ url_for('landing_page') }}" class="cancelled-btn">Annulation et retour à l'accueil</a>
            </div>
        </form>
    </div>
</div>

{% endblock %}

templates/user/devis_form_thanks.html
{% extends 'base2.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Page de remerciements pour une demande de devis sur le site de l'entreprise SethiarWorks.">
<title>{% block title %}Merci de votre demande de devis{% endblock %}</title>
{% endblock %}

{% block main_content %}
<div class="outer-frame-politique">
    <div class="inner-frame-politique">
        <main class="politique-main">
            <div class="politique-border">

                <!--titre -->
                <h1 class="politique-title">Remerciements de votre demande de devis</h1>

                <!-- Section : Mise à jour et retour -->
                <div class="politique-header">
                    <a href="{{ url_for('landing_page') }}" class="politique-home-link">Retour à l'accueil</a>
                </div>
            </div>

            <!-- Séparation -->
            <hr class="politique-divider">

            <!-- Logo -->
            <div class="politique-logo">
                <img src="{{ url_for('static', filename='Images/images_accueil/logo.jpg') }}"
                     alt="Logo de SethiarWorks"
                     class="politique-logo-img">
            </div>

            <!-- Contenu principal -->
            <div class="contact-content">

                <!-- Carte de visite SethiarWorks -->
                <div class="cart-sethiar">
                    <!-- Verso -->
                    <img src="{{ url_for('static', filename='Images/images_produit/cart_sethiar.png') }}"
                         alt="carte de visite de SethiarWorks"
                         class="SethiarCart-pic-contact">

                    <!-- Recto -->
                    <img src="{{ url_for('static', filename='Images/images_produit/cart_sethiar2.png') }}"
                         alt="carte de visite de SethiarWorks"
                         class="SethiarCart-pic-contact">
                </div>
            </div>
          <div class="annonce">
            <p>Nous vous remercions pour votre demande de devis et nous reviendrons très bientôt
              vers vous afin de vous informer de notre réponse concernant votre demande.</p>
            <div class="space2"></div>
              <p>Cordialement, l'équipe de SethiarWorks.</p>
          </div>
        </main>
    </div>
</div>
{% endblock %}
{% block footer_content %}
{% endblock %}

templates/user/edit_comment_subject.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Formulaire de modification d'un commentaire par l'utilisateur.">
<title>{% block title %}Modification d'un commentaire{% endblock %}</title>
{% endblock %}

{% block header_content %}

{% endblock %}

{% block body_content %}
<div class="outer-frame">
    <div class="inner-frame">

        <!-- Titre du formulaire -->
        <h2 class="h2-form">Voici le formulaire pour modifier un commentaire.</h2>

        <form method="POST" action="{{ url_for('user.change_comment', id=comment.id) }}" class="form-base">

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='Images/images_accueil/logo.jpg') }}"
                     alt="Logo de SethiarWorks"
                     class="avatar-form">
            </div>

            <!-- Titre de la section du formulaire -->
            <h3 class="h3-form">Modification du commentaire</h3>

            <!-- hidden_tag pour génération du token CSRF pour la sécurité -->
            {{ formchange.hidden_tag() }}

            <div class="space-form"></div>

            <!-- Conteneur de la modification du commentaire -->
            <div class="form-group">
                {{ formchange.comment_content.label }} {{ formchange.comment_content() }}
                <input type="hidden" name="subject_id" value="{{ comment.subject_id }}">
                <input type="hidden" name="comment_id" value="{{ comment.id }}">

                <div class="container-btn">
                    <button type="submit" class="validated-btn" aria-label="Valider la modification">Soumettre la
                        réponse
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/user/edit_reply_subject.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Formulaire de modification d'une réponse à un commentaire par l'utilisateur.">
<title>{% block title %}Modification d'une réponse à un commentaire{% endblock %}</title>
{% endblock %}

{% block header_content %}

{% endblock %}

{% block body_content %}
<div class="outer-frame">
    <div class="inner-frame">

        <!-- Titre du formulaire -->
        <h2 class="h2-form">Voici le formulaire pour modifier une réponse à un commentaire.</h2>
        <form method="POST" action="{{ url_for('user.change_reply', id=reply.id) }}" class="form-base">

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='Images/images_accueil/logo.jpg') }}"
                     alt="Logo de SethiarWorks"
                     class="avatar-form">
            </div>

            <!-- Titre de la section du formulaire -->
            <h3 class="h3-form">Modification de la réponse du commentaire</h3>

            <!-- hidden_tag pour génération du token CSRF pour la sécurité -->
            {{ formchangereply.hidden_tag() }}

            <div class="space-form"></div>

            <!-- Conteneur de la modification de la réponse au commentaire -->
            <div class="form-group">
                {{ formchangereply.reply_content.label }} {{ formchangereply.reply_content() }}
                <input type="hidden" name="comment_id" value="{{ reply.subject_id }}">
                <input type="hidden" name="reply_id" value="{{ reply.id }}">

                <div class="container-btn">
                    <button type="submit" class="validated-btn" aria-label="Valider la modification">Soumettre la
                        réponse
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/user/reply_form_subject.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Formulaire de réponse par un utilisateur au sujet posté sur le forum du blog.">
<title>{% block title %}Réponse au sujet du forum du blog{% endblock %}</title>
{% endblock %}

{% block header_content %}

{% endblock %}

{% block body_content %}
<div class="outer-frame">
    <div class="inner-frame">

        <!-- Titre du formulaire -->
        <h2 class="h2-form">Voici le formulaire pour écrire une réponse aux sujets postés sur le forum. </h2>

        <form method="POST" class="form-base"
              action="{{ url_for('user.comment_replies_subject', comment_subject_id=comment.id, user_pseudo=current_user.pseudo) }}">
            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='Images/images_accueil/logo.jpg') }}"
                     alt="Logo de SethiarWorks"
                     class="avatar-form">
            </div>

            <!-- Titre de la section du formulaire -->
            <h3 class="h3-form">Réponse au commentaire</h3>

            <!-- hidden_tag pour génération du token CSRF pour la sécurité -->
            {{ formsubjectreply.csrf_token }}

            <div class="space-form"></div>

            <!-- Conteneur de la réponse au commentaire -->
            <div class="form-group">
                {{ formsubjectreply.reply_content.label }} {{ formsubjectreply.reply_content() }}
                <input type="hidden" name="subject_id" value="{{ comment.subject_id }}">
                <input type="hidden" name="comment_id" value="{{ comment.id }}">

                <div class="container-btn">
                    <button type="submit" class="validated-btn" aria-label="Valider la réponse">Soumettre la réponse
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}